[package]
name = "models"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
yew = { version = "0.23", features = ["csr"] }
chrono = "0.4.44"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.9", features = ["sqlite", "runtime-tokio"] }
